name: web_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

#-------------PACKAGES ------------#

dependencies:
  flutter:
    sdk: flutter

#-------UTILITY PACKAGES -----------#



#-------ICONS--------#
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8


#------STATEMENT MANAGEMENT---------#
  get: ^4.6.5

#------ PRODUCT SPECIFIC ---------#



#------- ./ PACKAGES END -----------#


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true
#------- LOCAL ASETS----------#


   assets:
    - assets/logos/
    - assets/icons/
    - assets/amages/
#---------LOCAL FONTS ------------#

  fonts:
    - family: Poppins
      fonts:
        - assets: assets/fonts/Poppins-Light.ttf
          weight: 300
        - assets: assets/fonts/Poppons-Regular.ttf
          weight: 400
        - assets: assets/fonts/Poppins-Italic.ttf
          style: italic
        - assets: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - assets: assets/fonts/Poppins-MediumItalic.tff
          weight: 500
          style: italic
        - assets: assets/fonts/Poppins-SemiBold.tff
          weight: 600
        - assets: assets/fonts/Poppins-Bold.tff
          weight: 800
